name: game777
description: "game777"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  go_router: ^14.8.0
  get: ^4.7.2
  dio: ^5.8.0+1
  synchronized: ^3.1.0
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.3
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.2
  encrypt: ^5.0.3
  crypto: ^3.0.6
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  google_fonts: ^5.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/l10n/zh/common.json
    - assets/l10n/id/common.json


